---
ansible_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36633330323339316462616630323238633334636330343964613738336561643032313664646262
  3635373832313066383862653639393335363530616638610a393865613739643730303730613130
  34643736353135333034303933383739336535366239326132636631353836383161646332623062
  3933643136626430650a393537623261376336663666343864316432353934343261386431613662
  3566
ansible_ssh_private_key_file: ~/.ssh/vpl-datadvisor-001

ANSIBLE_ROLES:
  - docker
  - datadvisor

DOCKER_REGISTRY: ghcr.io
GITHUB_USERNAME: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30623137643334663639323135623538313165346466323165366565333265373262363865616664
  3561363832656639323033333338663031633735613633330a386236633265363161343062656566
  64373439633561383733353466356431643633356233633434393732303864643936396632386165
  3731376334626263660a653035306533373032373435386336646161323062616563616161646330
  3765
GITHUB_ACCESS_TOKEN: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64306539356432333565626433396564666131626262313939306530373935353163623631663863
  6237373935656334626365636130376435343530383061330a343439386539343663326662346363
  65353062643633656164373735663464646563363632373835353437353161626438303466316433
  6438643731336366310a383433646233363333626631646262376436373231616562343061303739
  36383839333935366136323431363230303530633563363761623763396335316332396565643537
  3839656239643065616165613136336361383461396235336366

ENV_TYPE: production

FRONTEND_IMAGE: frontend:latest
API_IMAGE: api:latest
SCRAPPER_IMAGE: scrapper:latest
NGINX_IMAGE: nginx:1.21.6-alpine
POSTGRES_IMAGE: postgres:14.3-alpine
REDIS_IMAGE: redis:7.0.0-alpine

DATADVISOR_SERVICES:
  - frontend
  - api
  - scrapper
  - nginx
  - postgres
  - redis

FRONTEND_PORT: 3000
API_PORT: 3001

NGINX_FRONTEND_URL: datadvisor.me
NGINX_API_URL: api.datadvisor.me

NGINX_FRONTEND_LOG_FILENAME: frontend-prod
NGINX_API_LOG_FILENAME: api-prod
