# Description: main.yml - Ansible playbook
# Author: Lorenzo Carneli <lorenzo.carneli@epitech.eu>

---
- hosts: all
  become: true
  tasks:
    - include_role:
        name: "{{ role }}"
      loop:
        "{{ ANSIBLE_ROLES }}"
      loop_control:
        loop_var: role
